### ISSUE TITLE
I could NOT install mrpt-bridge in Ubuntu 18.04 Melodic. 

### ISSUE THREAD

**Issue by leizhao3** [mrpt-ros-pkg/mrpt_bridge#10]
Hi There,recently I'm trying to install mrpt-bridge in Ubuntu 18.04 Melodic of my Odroid UX4. Unfortunately, I'm encountering difficulty below: 

code ran: 
`~/catkin_ws/src $ git clone https://github.com/mrpt-ros-pkg/mrpt_bridge/tree/ros1 #add mrpt_bridge package`
`~/catkin_ws/src $cd ..`
`~/catkin_ws$ sudo apt-get update`
`~/catkin_ws $ catkin_make`

Error:
> CMake Error at /usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
> Could not find a configuration file for package "mrpt-typemeta" that is
> compatible with requested version "".
> 
> The following configuration files were considered but not accepted:
> 
> /usr/share/mrpt-typemeta/mrpt-typemeta-config.cmake, version: 2.1.3 (64bit)

Couldn't find anything online about how to fix this issue. Does anyone could help me out here? Appreciate your input~

**Comment by jlblancoc** [comment]
Hi, 
Where did you get mrpt installed from? Check, for example, the output of:
```bash
dpkg --list | grep mrpt
apt-cache madison libmrpt-dev
```

**Comment by leizhao3** [comment]
Hi @jlblancoc , thank you so much for your response! I'm able to solve this issue by following code: 
`rosdep install --from-paths src --ignore-src -r -y`
