### ISSUE TITLE
ros noetic catkin_make error

### ISSUE THREAD

**Issue by 3shao** [mrpt-ros-pkg/mrpt_bridge#11]
`/home/robot/dashgo_ws/src/mrpt_bridge/src/imu.cpp: In function ‘bool mrpt_bridge::imu::mrpt2ros(const mrpt::obs::CObservationIMU&, const Header&, sensor_msgs::Imu&)’:
/home/robot/dashgo_ws/src/mrpt_bridge/src/imu.cpp:53:36: error: conversion from ‘const std::array<double, 31>’ to non-scalar type ‘std::vector<double, std::allocator<double> >’ requested
   53 |  vector<double> measurements = obj.rawMeasurements;
      |                                ~~~~^~~~~~~~~~~~~~~
make[2]: *** [mrpt_bridge/CMakeFiles/mrpt_bridge.dir/build.make:102: mrpt_bridge/CMakeFiles/mrpt_bridge.dir/src/imu.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
`
how can I fix it ?

**Comment by jlblancoc** [comment]
Fixed via #12
