### ISSUE TITLE
ROS:Time to tTimestamp conversion

### ISSUE THREAD

**Issue by JGMonroy** [mrpt-ros-pkg/mrpt_bridge#5]
Hi there,
Got an error while compiling the mrpt_brigde repo, and after taking a look, I do not completely understand the way the conversions in the time.h file are handled.

For example:
```c++
inline void convert(const ros::Time& src, mrpt::system::TTimeStamp& des)
{
    // Original is (rising compilation errors):
    des = mrpt::system::time_tToTimestamp((time_t)src.sec) + src.nsec / 100;
    // While a more "easy" way is:
    des = mrpt::system::time_tToTimestamp( (time_t)src.toSec() );   
}
```

Similarlay:
```c++
inline void convert(const mrpt::system::TTimeStamp& src, ros::Time& des)
{
    // Original rising compilation issues is: 
    des.sec = ((uint64_t)src) / ((uint64_t)10000000) -
        (((uint64_t)116444736) * ((uint64_t)100));
    des.nsec = ((uint64_t)src) % ((uint64_t)10000000) * 100;
    // While a "easy" conversion would be:
    time_t src_time_t = mrpt::system::timestampTotime_t(src);
    des.fromSec(src_time_t);
}
```

I think I'm missing something, because I do not understand why "116444736" is needed. Maybe both time representation are not using the same epoch?

I want to discuss before making a PR.
Thanks.

**Comment by jlblancoc** [comment]
Hi! I'll try to check what compile errors are this causing during this weekend. 

However, a quick note on this: 


```
 // While a more "easy" way is:
    des = mrpt::system::time_tToTimestamp( (time_t)src.toSec() );   
```

Note that time_t is integral, so the typecast would lose the fractions of seconds (!), so don't try that! :-)

**Comment by jlblancoc** [comment]
PS: Please, check what version of MRPT 1.9.9 do you have in your system... we recently (~1 mo ago) made changes to all the time area (though, in theory most were backwards compatible), and I could swear I checked that this ROS package was up-to-date with those changes... But may be it's not

**Comment by jlblancoc** [comment]
Ok, I know what happened... it's simply that all ROS packages are configured such that they always built in all build farms against mrpt-1.5, so the latest changes in the TTimeStamp area for mrpt2 wasn't tested in ROS! 
I'll submit a patch. 

Thanks for reporting! ;-)
